# Generated by Django 6.0.8 on 2026-08-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='portfolio_b_publish_b030df_idx',
            old_name='portfolio_b_publishe_3c5b53_idx',
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='portfolio_c_is_revi_b3125e_idx',
            old_name='portfolio_c_is_revie_7e92b3_idx',
        ),
        migrations.RenameIndex(
            model_name='highvolumelogentry',
            new_name='portfolio_h_action__f52263_idx',
            old_name='portfolio_h_action_c_1d760e_idx',
        ),
        migrations.RenameIndex(
            model_name='highvolumelogentry',
            new_name='portfolio_h_visitor_62f8d0_idx',
            old_name='portfolio_h_visitor__bf5c1e_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='portfolio_p_feature_02a815_idx',
            old_name='portfolio_p_feature_87d776_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='portfolio_p_categor_cb0b95_idx',
            old_name='portfolio_p_category_8e8e0b_idx',
        ),
        migrations.RenameIndex(
            model_name='skill',
            new_name='portfolio_s_categor_8a1c04_idx',
            old_name='portfolio_s_category_79c302_idx',
        ),
    ]
